version: '3'
services:
  node-app:
    container_name: nodejs-app
    restart: always
    build: .
    environment:
      - PORT=4001
      - EXPIRE_AFTER_DAYS=10
      - REDIS_URL=redis://cache:6379
    ports: 
      - '4001:4001'
    depends_on: 
      - cache
    networks:
      - backend

  cache:
    container_name: redis-service-container
    image: redis
    ports:
      - 6379:6379
    networks:
      - backend
networks:
  backend: